name: Build, publish and deploy project to Simply

on: [push]

jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
          
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish SmarteraspGithub/SmarteraspGithub.csproj --configuration Release --output ./publish --runtime win-x86 --self-contained false -p:PublishTrimmed=false -p:PublishSingleFile=false
        
      - name: Test with .NET
        run: dotnet test

      - name: Deploy to Simply        
        uses: talunzhang/auto-web-deploy@v1.0.1
        with:
          website-name: ricappssolutions-002-site7
          server-computer-name: https://win5077.site4now.net:8172
          server-username: ricappssolutions-002
          server-password: RicPa@@w0rd
      # Leave extra files on Server
          target-delete: false
          
      #   website-name: ${{ secrets.WEBSITE_NAME }
      #   server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
      #   server-username: ${{ secrets.SERVER_USERNAME }}
      #   server-password: ${{ secrets.SERVER_PASSWORD }}
      #   target-delete: true
